const projects = [
 {id:'coffee',name:'Coffee & More',type:'CAFE / SERVİS & TEŞHİR',image:'coffee-concept',accent:'#ddc7a7',line:'Taşın çizgisi. Ahşabın sıcaklığı.',materials:['Mermer görünümü','Ahşap cephe','Cam teşhir'],description:'Dalgalı ön cephe, ahşap yüzeyler ve aydınlatılmış isimlik. Servis bankosu ile tatlı vitrini aynı çizgide buluşuyor.',gallery:['coffee-concept','coffee-real']},
 {id:'garden',name:'Bahçe Kafe',type:'CAFE / AÇIK ALAN',image:'garden',accent:'#b9e0cb',line:'Doğanın içinde, kendi ritminde.',materials:['Mint renkli cephe','Açık renk tezgâh','Sıcak aydınlatma'],description:'Yeşilliklerin arasındaki servis hattı. Açık renkli banko, kahve hazırlık alanı ve cam vitrin bahçenin atmosferine eşlik ediyor.',gallery:['garden']},
 {id:'doner',name:'Döner Restoranı',type:'RESTORAN / HAZIRLIK & SERVİS',image:'doner',accent:'#cdac82',line:'Her çizgide bir düzen.',materials:['Ahşap çıtalar','Siyah çerçeveler','Köşeli yerleşim'],description:'Hazırlık, teşhir ve kasa alanlarını çevreleyen köşeli servis bankosu. Ahşap cephe ve siyah yüzeyler mekânın çizgisini belirliyor.',gallery:['doner']},
 {id:'bakery',name:'Pastane',type:'PASTANE / TEŞHİR & ÇALIŞMA',image:'bakery',accent:'#d2b08c',line:'Önünde sunum. Arkasında emek.',materials:['Ahşap paneller','Çok katlı teşhir','Arka çalışma alanı'],description:'Geniş cam yüzeyler ve farklı teşhir bölümleri. Ön cepheden çalışma tarafına uzanan üç açı, projenin yerleşimini birlikte anlatıyor.',gallery:['bakery','bakery-front','bakery-back']},
 {id:'baklava',name:'Baklava Vitrini',type:'PASTANE / TATLI TEŞHİRİ',image:'baklava',accent:'#e4bc64',line:'Işık, dokuyu ortaya çıkarır.',materials:['Sıcak ahşap','Koyu metal','Eğimli teşhir camı'],description:'Koyu tonlu mekânda sıcak ışıklarla öne çıkan uzun teşhir hattı. Köşe dönüşü ve farklı vitrin yükseklikleri sunuma ritim katıyor.',gallery:['baklava']}
];
const $=s=>document.querySelector(s), menu=$('#menu'),toggle=$('#menu-toggle'),dialog=$('#details');
function closeMenu(){menu.hidden=true;toggle.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open');$('#journey').inert=false;$('.interface').inert=false;}
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';menu.hidden=!open;toggle.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open);$('#journey').inert=open;$('.interface').inert=open;if(open)menu.querySelector('a').focus();});
menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();}});
$('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
let currentProject=0;
function openDetails(index){const p=projects[index];$('#detail-content').innerHTML=`<p class="eyebrow">${p.type}</p><h2 id="detail-title">${p.name}</h2><p class="detail-description">${p.description}</p>${p.id==='coffee'?`<div class="comparison"><img src="assets/coffee-real.webp" alt="Coffee & More ikinci görünüm"><div class="comparison-overlay"><img src="assets/coffee-concept.webp" alt="Coffee & More ilk görünüm"></div><span class="compare-label left">GÖRÜNÜM 01</span><span class="compare-label right">GÖRÜNÜM 02</span><input type="range" min="0" max="100" value="50" aria-label="İki proje görselini karşılaştır"></div>`:p.gallery.map((img,i)=>`<figure><img src="assets/${img}.webp" alt="${p.name}, görünüm ${i+1}" loading="lazy"><figcaption>GÖRÜNÜM 0${i+1} / ${p.name}</figcaption></figure>`).join('')}<div class="detail-materials">${p.materials.map(m=>`<span>${m}</span>`).join('')}</div>`;const range=dialog.querySelector('input');if(range)range.addEventListener('input',()=>$('.comparison').style.setProperty('--split',range.value+'%'));dialog.showModal();}
$('#discover').addEventListener('click',()=>openDetails(currentProject));
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),pointer={x:0,y:0};let world=null,lastChapter=-99,positions=[];
function measure(){positions=[...document.querySelectorAll('.scroll-chapter')].map(s=>({top:s.offsetTop,height:s.offsetHeight}));}
measure();addEventListener('resize',measure);let touchStart=null;$('#world').addEventListener('pointerdown',e=>{if(e.pointerType==='touch')touchStart={x:e.clientX,start:pointer.x};});addEventListener('pointermove',e=>{if(e.pointerType==='mouse'){pointer.x=e.clientX/innerWidth*2-1;pointer.y=e.clientY/innerHeight*2-1;}else if(touchStart){pointer.x=Math.max(-2,Math.min(2,touchStart.start+(e.clientX-touchStart.x)/innerWidth*4));}},{passive:true});addEventListener('pointerup',()=>touchStart=null);addEventListener('pointercancel',()=>touchStart=null);
function stateAt(y){let index=0;while(index<positions.length-1&&y>=positions[index+1].top)index++;const r=positions[index];return {chapter:index-1,local:Math.min(1,Math.max(0,(y-r.top)/r.height))};}
function paintUI(state){const {chapter,local}=state;const intro=chapter===-1,end=chapter===5;$('#opening-copy').hidden=!intro;$('#closing-copy').hidden=!end;$('#project-copy').hidden=intro||end;if(chapter!==lastChapter){lastChapter=chapter;if(chapter>=0&&chapter<5){currentProject=chapter;const p=projects[chapter];$('#project-type').textContent=p.type;$('#project-name').textContent=p.name;$('#project-line').textContent=p.line;document.documentElement.style.setProperty('--accent',p.accent);$('#material-label').textContent=p.materials.join(' · ');}else document.documentElement.style.setProperty('--accent','#d5edaa');}
 const photo=local>.63,assembling=local<.3;document.body.classList.toggle('model-phase',!photo);$('#stage-label').textContent=intro?'01 / PARÇADAN BÜTÜNE':end?'YENİ BİR BAŞLANGIÇ':`${String(chapter+1).padStart(2,'0')} / ${photo?'MEKÂNIN İÇİNDE':assembling?'BİR ARAYA GELİYOR':'FARKLI BİR AÇIDAN'}`;
 $('#model-step').textContent=intro?'KAYDIR / BİRLEŞTİR':photo?'MEKÂNI KEŞFET':assembling?'01 — OLUŞUM':'02 — PERSPEKTİF';$('#model-label').style.opacity=end?'0':photo?'0':'1';$('#chapter-number').textContent=String(Math.max(0,Math.min(5,chapter+1))).padStart(2,'0');const percent=Math.min(1,scrollY/(document.documentElement.scrollHeight-innerHeight));$('#progress').style.height=percent*100+'%';$('#scroll-percent').textContent=String(Math.round(percent*100)).padStart(2,'0')+'%';$('#scroll-hint').innerHTML=intro?'Kaydır. Mekânı oluştur. <b>↓</b>':end?'Yeni bir hikâye başlasın.':'Kaydır. Perspektifi değiştir. <b>↓</b>';
 const fade=intro?Math.max(0,1-(local-.55)*3):end?1:Math.max(.3,1-Math.max(0,local-.92)*9);const copy=intro?$('#opening-copy'):end?$('#closing-copy'):$('#project-copy');copy.style.opacity=fade;copy.style.transform=`translateY(${(1-fade)*-35}px)`;
}
let smoothY=scrollY,lastTime=0,active=true;
function frame(time){if(!active)return;const dt=Math.min(.05,(time-lastTime)/1000||.016);lastTime=time;smoothY=reduced.matches?scrollY:smoothY+(scrollY-smoothY)*(1-Math.exp(-dt*12));if(Math.abs(scrollY-smoothY)<.5)smoothY=scrollY;const state=stateAt(smoothY);paintUI(state);if(world)world.update(state,pointer,time/1000,reduced.matches);requestAnimationFrame(frame);}
document.addEventListener('visibilitychange',()=>{active=!document.hidden;if(active){lastTime=0;requestAnimationFrame(frame);}});
async function start(){try{const {createWorld}=await import('./world.js');world=await createWorld($('#world'),projects,value=>$('#loading i').style.width=value*100+'%');}catch(error){console.error('3D scene could not start:',error);$('#fallback').hidden=false;menu.querySelectorAll('a').forEach((a,i)=>{if(i<5)a.addEventListener('click',()=>openDetails(i));});}finally{$('#loading').hidden=true;requestAnimationFrame(frame);}}
start();
