import * as THREE from './vendor/three.module.js';
const clamp=THREE.MathUtils.clamp,lerp=THREE.MathUtils.lerp;
const ease=t=>{t=clamp(t,0,1);return t*t*(3-2*t);};
const ramp=(t,a,b)=>ease((t-a)/(b-a));

export async function createWorld(container,projects,onProgress){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});
 renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.5:1.75));renderer.setSize(innerWidth,innerHeight);renderer.setClearColor(0x10120f);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;container.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x10120f,.025);const camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,100);scene.add(camera);
 scene.add(new THREE.HemisphereLight(0xe9f5d7,0x4b3a27,2.6));
 const key=new THREE.DirectionalLight(0xffecd5,4);key.position.set(3,7,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-10,right:10,top:10,bottom:-10,near:.1,far:30});key.shadow.bias=-.0004;scene.add(key);
 const rim=new THREE.DirectionalLight(0xc9f5d8,3);rim.position.set(-6,4,-3);scene.add(rim);const fill=new THREE.DirectionalLight(0xe0eaff,1.5);fill.position.set(2,2,-7);scene.add(fill);
 const envScene=new THREE.Scene();envScene.background=new THREE.Color(0x758071);const panelMat=new THREE.MeshBasicMaterial({color:0xffffff});for(const [x,y,z,sx,sy,sz]of [[0,6,0,12,.1,8],[5,2,0,.1,6,9],[-5,2,0,.1,5,6]]){const panel=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),panelMat);panel.position.set(x,y,z);envScene.add(panel);}const pmrem=new THREE.PMREMGenerator(renderer);const env=pmrem.fromScene(envScene,0);scene.environment=env.texture;pmrem.dispose();
 const loader=new THREE.TextureLoader();let loaded=0;const total=7;async function texture(name){const t=await loader.loadAsync(`assets/${name}.webp`);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());onProgress(++loaded/total);return t;}
 const [woodMap,marbleMap,...photos]=await Promise.all([texture('wood'),texture('marble'),...projects.map(p=>texture(p.image))]);woodMap.wrapS=woodMap.wrapT=THREE.RepeatWrapping;marbleMap.wrapS=marbleMap.wrapT=THREE.RepeatWrapping;
 const materials={metal:new THREE.MeshStandardMaterial({color:0x141a18,metalness:.65,roughness:.32}),steel:new THREE.MeshStandardMaterial({color:0xa5ada8,metalness:.9,roughness:.24}),wood:new THREE.MeshStandardMaterial({map:woodMap,color:0xd0a16a,roughness:.46}),stone:new THREE.MeshStandardMaterial({map:marbleMap,color:0xe4e5dd,roughness:.28}),darkStone:new THREE.MeshStandardMaterial({color:0x232824,metalness:.25,roughness:.24}),glass:new THREE.MeshPhysicalMaterial({color:0xc7e8dd,metalness:0,roughness:.05,transparent:true,opacity:.18,side:THREE.DoubleSide,depthWrite:false,envMapIntensity:1.8}),gold:new THREE.MeshStandardMaterial({color:0xc59743,metalness:.75,roughness:.27}),white:new THREE.MeshStandardMaterial({color:0xe5e4d8,roughness:.24}),pastry:new THREE.MeshStandardMaterial({color:0xc99444,roughness:.72}),led:new THREE.MeshStandardMaterial({color:0xffce7f,emissive:0xffad3e,emissiveIntensity:3})};
 const unitBox=new THREE.BoxGeometry(1,1,1),unitCylinder=new THREE.CylinderGeometry(1,1,1,24),sphere=new THREE.SphereGeometry(1,16,10);
 function box(parent,w,h,d,x,y,z,mat){const m=new THREE.Mesh(unitBox,mat);m.scale.set(w,h,d);m.position.set(x,y,z);m.castShadow=mat!==materials.glass;m.receiveShadow=true;parent.add(m);return m;}
 function cylinder(parent,r,h,x,y,z,mat){const m=new THREE.Mesh(unitCylinder,mat);m.scale.set(r,h,r);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 function label(text){const c=document.createElement('canvas');c.width=1024;c.height=256;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.font='500 85px Georgia';ctx.textAlign='center';ctx.fillStyle='#f4eddc';ctx.shadowColor='#ffcf7b';ctx.shadowBlur=12;ctx.fillText(text,512,165);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshBasicMaterial({map:t,transparent:true,depthWrite:false});}
 function counter(index){const root=new THREE.Group();const parts=[];function part(name,offset){const g=new THREE.Group();g.name=name;g.userData.offset=new THREE.Vector3(...offset);root.add(g);parts.push(g);return g;}
  const base=part('base',[0,-.65,.4]),front=part('facade',[-.75,.15,.8]),top=part('stone',[0,.9,-.15]),glass=part('glass',[.6,1.15,-.2]),equipment=part('equipment',[-.5,1.65,-1]),lamps=part('lights',[0,.8,0]);
  const wood=index===1?new THREE.MeshStandardMaterial({color:0x9fcbbb,roughness:.44}):materials.wood;const stone=index===2||index===3||index===4?materials.darkStone:materials.stone;
  box(base,6,.16,1.45,0,.16,0,materials.metal);box(base,5.82,1,1.2,0,.73,-.04,materials.metal);
  const slats=new THREE.InstancedMesh(unitBox,wood,72);const matrix=new THREE.Matrix4();for(let i=0;i<72;i++){matrix.compose(new THREE.Vector3(-2.94+i*.083, .76,.7),new THREE.Quaternion(),new THREE.Vector3(.061,1.05,.06));slats.setMatrixAt(i,matrix);}slats.castShadow=true;slats.receiveShadow=true;front.add(slats);
  box(front,6,.09,.06,0,.23,.73,materials.metal);box(front,6,.09,.06,0,1.27,.73,materials.metal);box(front,5.88,.025,.07,0,.22,.77,materials.led);
  box(top,6.14,.13,1.6,0,1.37,0,stone);
  if(index===0){const curve=new THREE.Shape();curve.moveTo(-3.07,1.44);curve.lineTo(3.07,1.44);curve.lineTo(3.07,1.2);curve.bezierCurveTo(1.8,1.2,.7,.9,-.1,.98);curve.bezierCurveTo(-1.1,1.06,-1.9,1.01,-3.07,1.02);curve.closePath();const fascia=new THREE.Mesh(new THREE.ExtrudeGeometry(curve,{depth:.06,bevelEnabled:true,bevelSize:.014,bevelThickness:.014,bevelSegments:2,steps:1,curveSegments:24}),materials.stone);fascia.position.z=.77;fascia.castShadow=true;top.add(fascia);const sign=new THREE.Mesh(new THREE.PlaneGeometry(2.5,.48),label('Coffee & More'));sign.position.set(-1.48,1.22,.86);top.add(sign);}
  if(index===2){box(base,1.5,1.16,1.5,-2.26,.7,-1.38,materials.metal);box(top,1.6,.13,1.8,-2.27,1.37,-1.6,stone);for(let j=0;j<17;j++)box(front,.063,1.05,.06,-2.95+j*.086,.76,-2.45,wood);}
  if(index===3){for(let i=0;i<3;i++)box(front,1.45,.05,.07,-1.85+i*1.85,.83,.78,materials.metal);}
  const vw=index===4?5.7:index===3?3.5:2.6,vx=index===4?0:index===3?.95:1.65,depth=1.2,gh=index===4?1.1:1.35;
  box(glass,vw,.065,depth,vx,1.46,0,materials.metal);box(glass,vw,.06,depth,vx,1.46+gh,0,materials.metal);
  for(const x of [vx-vw/2,vx,vx+vw/2])for(const z of [-depth/2,depth/2])box(glass,.04,gh,.04,x,1.46+gh/2,z,materials.metal);
  const frontGlass=box(glass,vw,gh,.016,vx,1.46+gh/2,.605,materials.glass);if(index===4)frontGlass.rotation.x=-.15;box(glass,.016,gh,depth,vx-vw/2,1.46+gh/2,0,materials.glass);box(glass,.016,gh,depth,vx+vw/2,1.46+gh/2,0,materials.glass);box(glass,vw,.016,depth,vx,1.46+gh,0,materials.glass);
  for(let row=0;row<3;row++){const yy=1.51+row*(gh/3);box(glass,vw-.09,.025,depth-.07,vx,yy,0,materials.glass);box(glass,vw-.13,.018,.025,vx,yy,-.56,materials.led);const count=index===4?16:index===3?10:7;for(let k=0;k<count;k++){const x=vx-vw*.45+k*(vw*.9/(count-1));const treat=new THREE.Mesh(sphere,materials.pastry);treat.scale.set(index===4?.12:.14,.055,.12);treat.position.set(x,yy+.075,.16);glass.add(treat);const plate=cylinder(glass,.16,.014,x,yy+.02,.16,materials.white);}}
  if(index!==4&&index!==2){box(equipment,1.35,.62,.55,-1.55,1.75,-.22,materials.metal);box(equipment,1.3,.08,.58,-1.55,2.06,-.22,materials.steel);box(equipment,1.32,.045,.76,-1.55,1.45,-.03,materials.steel);for(let k=0;k<3;k++){cylinder(equipment,.025,.19,-1.95+k*.38,1.7,.12,materials.steel);const knob=cylinder(equipment,.07,.05,-1.95+k*.38,1.89,.08,materials.gold);knob.rotation.x=Math.PI/2;}for(let k=0;k<5;k++)cylinder(equipment,.1,.09,-2+k*.2,2.14,-.22,materials.white);box(equipment,.15,.12,.16,-.47,1.48,.2,materials.metal);const screen=box(equipment,.4,.35,.05,-.47,1.72,.14,materials.metal);screen.rotation.x=-.3;
  for(let k=0;k<2;k++){cylinder(equipment,.12,.22,-2.55+k*.3,1.58,.28,materials.white);const handle=new THREE.Mesh(new THREE.TorusGeometry(.06,.015,6,12),materials.white);handle.position.set(-2.43+k*.3,1.58,.28);equipment.add(handle);}}
  if(index===2){box(equipment,4.2,1.18,.8,-.3,.72,-2,materials.steel);box(equipment,4.3,.08,.9,-.3,1.35,-2,materials.darkStone);box(equipment,4.5,.5,1.15,-.3,3.35,-2,materials.steel);const meat=new THREE.MeshStandardMaterial({color:0xb77f46,roughness:.9});const profile=[[.13,0],[.17,.08],[.19,.25],[.23,.5],[.28,.8],[.3,1.0],[.23,1.08]].map(([x,y])=>new THREE.Vector2(x,y));const skewerGeometry=new THREE.LatheGeometry(profile,24);for(let j=0;j<4;j++){const x=-1.8+j;box(equipment,.66,.11,.65,x,1.45,-1.85,materials.metal);box(equipment,.58,1.3,.06,x,2.1,-2.14,materials.metal);const spit=cylinder(equipment,.014,1.3,x,2.1,-1.82,materials.steel);const cone=new THREE.Mesh(skewerGeometry,meat);cone.position.set(x,1.56,-1.82);cone.castShadow=true;equipment.add(cone);for(let k=0;k<9;k++)cylinder(equipment,.15+k*.017,.012,x,1.58+k*.1,-1.82,materials.pastry);}}
  if(index===3){box(equipment,2.5,2.5,.13,1.5,2.2,-1.5,wood);for(let r=0;r<3;r++){box(equipment,2.5,.06,.44,1.5,1.3+r*.76,-1.28,materials.metal);for(let k=0;k<6;k++){const bread=new THREE.Mesh(sphere,materials.pastry);bread.position.set(.55+k*.37,1.48+r*.76,-1.26);bread.scale.set(.12,.24,.12);bread.rotation.z=-.15;equipment.add(bread);}}}
  const bellPoints=[[.36,0],[.35,.06],[.31,.14],[.24,.23],[.13,.29],[.05,.32]].map(([x,y])=>new THREE.Vector2(x,y));const bellGeometry=new THREE.LatheGeometry(bellPoints,32);for(let k=0;k<3;k++){const x=-2.1+k*2.1;const lamp=new THREE.Mesh(bellGeometry,materials.metal);lamp.position.set(x,3.5,-.04);lamp.castShadow=true;lamps.add(lamp);cylinder(lamps,.022,.64,x,4.13,-.04,materials.metal);cylinder(lamps,.045,.17,x,3.91,-.04,materials.gold);cylinder(lamps,.3,.015,x,3.5,-.04,materials.led);}
  root.userData.parts=parts;return root;
 }
 const models=projects.map((_,i)=>{const m=counter(i);m.visible=false;scene.add(m);return m;});
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({color:0x000000,opacity:.3}));floor.rotation.x=-Math.PI/2;floor.position.y=-.04;floor.receiveShadow=true;scene.add(floor);
 const ring=new THREE.Mesh(new THREE.RingGeometry(4.25,4.26,120),new THREE.MeshBasicMaterial({color:0x718366,transparent:true,opacity:.22,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.001;scene.add(ring);
 const wireGroup=new THREE.Group();scene.add(wireGroup);const lineMaterial=new THREE.LineBasicMaterial({color:0xb3d18e,transparent:true,opacity:.18});const blueprint=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(6.14,1.44,1.6)),lineMaterial);blueprint.position.y=.72;wireGroup.add(blueprint);
 const photoRoot=new THREE.Group();camera.add(photoRoot);const photoMeshes=photos.map(t=>{const mesh=new THREE.Mesh(new THREE.PlaneGeometry(1,1),new THREE.MeshBasicMaterial({map:t,transparent:true,opacity:1,side:THREE.DoubleSide,fog:false}));mesh.visible=false;photoRoot.add(mesh);return mesh;});
 const target=new THREE.Vector3(),camPosition=new THREE.Vector3();let mobile=innerWidth<700,previous=-99;
 function resize(){mobile=innerWidth<700;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.5:1.75));renderer.setSize(innerWidth,innerHeight);}
 addEventListener('resize',resize);
 function update(state,pointer,time,reduced){const {chapter,local}=state;const intro=chapter===-1,end=chapter===5,index=clamp(chapter,0,4),model=models[index];if(previous!==index){models.forEach((m,i)=>m.visible=i===index);photoMeshes.forEach((m,i)=>m.visible=i===index);previous=index;}
  const assemble=reduced?1:intro?ramp(local,.05,.68):chapter===0?1:ramp(local,.02,.29),orbit=reduced?0:intro?ramp(local,.5,1):ramp(local,.3,.62),portal=intro?0:reduced?(end||local>.65?1:0):end?ramp(local,0,.55):ramp(local,.62,.81),exit=reduced||intro||end?0:ramp(local,.91,1);
  const explode=reduced?0:(1-assemble);model.userData.parts.forEach((part,i)=>{part.position.copy(part.userData.offset).multiplyScalar(explode);part.rotation.set(explode*(i%2?-.15:.13),explode*(i%2?.13:-.11),explode*(i-2)*.03);});
  model.visible=portal<.99&&!end;
  const yaw=intro?lerp(-.65,-.4,orbit):lerp(-.4,1.0,orbit);model.rotation.set(0,reduced?-.35:yaw+pointer.x*(mobile?.28:.08),0);model.position.set(intro?(mobile?0:lerp(2.05,1,orbit)):lerp(mobile?0:1.0,-3.5,portal),mobile?-1.9:0,0);model.scale.setScalar(intro?(mobile?lerp(.74,.78,orbit):lerp(.87,1,orbit)):mobile?.78:1);
  if(!reduced&&intro)model.position.y+=Math.sin(time*.7)*.05;
  const cameraZ=mobile?20.2:intro?lerp(11.6,10.7,orbit):lerp(10.7,8.5,orbit);camPosition.set(intro?lerp(0,.3,orbit):lerp(.3,1.0,orbit),mobile?4.6:4.5,cameraZ);target.set(intro?(mobile?0:lerp(.2,0,orbit)):0,mobile?1.35:1.5,0);camera.position.copy(camPosition);camera.lookAt(target);if(!mobile&&!reduced)camera.rotation.z=pointer.x*.006;
  floor.position.y=mobile?-2.2:-.04;wireGroup.position.copy(model.position);wireGroup.rotation.copy(model.rotation);wireGroup.scale.copy(model.scale);wireGroup.visible=!end&&portal<.1;lineMaterial.opacity=explode*.2;ring.position.set(model.position.x,floor.position.y+.01,0);ring.material.opacity=(1-portal)*.16;
  const photo=photoMeshes[index];photo.visible=portal>.001||end;const dist=lerp(8,4.9,portal);const screenHeight=2*dist*Math.tan(THREE.MathUtils.degToRad(camera.fov/2)),screenWidth=screenHeight*camera.aspect;const image=photos[index].image,ratio=image.width/image.height;const height=Math.max(screenHeight,screenWidth/ratio),width=height*ratio;photo.scale.set(width*lerp(.38,1.025,portal)*(1+exit*.6),height*lerp(.38,1.025,portal)*(1+exit*.6),1);photo.position.set(lerp(screenWidth*.65,0,portal)+exit*screenWidth*.9,lerp(-screenHeight*.1,0,portal),-dist+exit*3);photo.rotation.set(0,reduced?0:lerp(-.8,0,portal)+exit*.6,reduced?0:exit*-.22);photo.material.opacity=portal*(1-exit);if(end){photo.material.opacity=1;photo.position.set(0,0,-5);photo.scale.set(width,height,1);photo.rotation.set(0,0,0);}
  if(end){renderer.setClearColor(0x10120f);}renderer.render(scene,camera);
 }
 renderer.compile(scene,camera);onProgress(1);return {update};
}
